package JeInOne.WeGong.Enums;

public enum musicGenre {
    POP, BALLAD, CLASSIC, COUNTRY, RNB, BLUES, FOLK, JAZZ, FUNK, ROCK, METAL, HIPHOP, ELECTRONIC, REGGAE, DANCE, PUNK,
    INDIE, LATIN, KPOP, JPOP, SOUNDTRACK, AMBIENT, FUSION, GOSPEL, MUSICAL, PROGRESSIVE, ETC
}
